### ISSUE TITLE
No longer works on react-native 0.56.0

### ISSUE THREAD

**Issue by a-koka** [Ajackster/react-native-global-props#11]
Is there an intent to keep this lib up to date?

**Comment by Ajackster** [comment]
Can you be more specific? I don't use React Native on a daily basis, but do intend to keep this lib relevant.

**Comment by Ajackster** [comment]
Closing this, refer to this [issue](https://github.com/Ajackster/react-native-global-props/issues/12) @a-koka if you are seeing a different issue, feel free to comment and let me know what the issue you're running into.

**Comment by a-koka** [comment]
@Ajackster the lib just doesn't work on react-native 0.56.0. I'm also using `Text.defaultProps` to set some other props and that no longer works either. I was using `setCustomTextInput` and `setCustomText` but I'm sure most methods are broken.

**Comment by rahimrahman** [comment]
I actually seeing this issue on my project.  I can create a new app using 0.56.0 using setCustomText and reproduce the error.
