### ISSUE TITLE
Should this library be linked?

### ISSUE THREAD

**Issue by angly-cat** [Ajackster/react-native-global-props#13]
There're `ios` and `android` folders in this repo, and this library links automatically if `react-native link` command is run. However, In my project it isn't linked, and... it works just fine? At least the subset of features that I use.

Can you describe for what functionality should this library be linked? Are these from the example, maybe?

**Comment by shukerullah** [comment]
This is very annoying whenever I run `react-native link` command, this library is linked.

**Comment by mCodex** [comment]
Yes, it should be linked. I'm currently using RN 0.57 and what I've done so far is: `react-native link react-native-global-props` and then I go to Xcode and then:

- Click in my project
- Go to `Build Phases`
- Click in `Link Binary With Libraries`
- Remove `ReactNativeGlobalProps.app` and `ReactNativeGlobalProps.test` (something like that)
And build

**Comment by angly-cat** [comment]
@mCodex why linking and then removing? Wasn't it working before you linked it?

**Comment by maieonbrix** [comment]
@Ajackster can we delete those folders ?

**Comment by Ajackster** [comment]
@maieonbrix Yeah, we can remove them. I think I made this project using the react-native init command which included a bunch of files that can be removed since this library is just a couple utility functions.

**Comment by maieonbrix** [comment]
I am on it, will open a PR in the following hours

**Comment by Ajackster** [comment]
Awesome, thanks :)
