### ISSUE TITLE
proptypes render Error

### ISSUE THREAD

**Issue by mr-riiim** [Ajackster/react-native-global-props#16]
hey guys
i added this package in a pure react-native project that created by **react-native-cli** .
and after run i get this error ! **in android and IOS**

### **undefined is not an object (evaluating '_reactNative.Text.prototype.render')**

![simulator screen shot - iphone 6 - 2018-10-11 at 10 35 55](https://user-images.githubusercontent.com/7345325/46786348-72f49500-cd41-11e8-9f06-5d4d8001ac1e.png)

### **this is my app Code:**  
`import React, { Component } from "react";
import { Platform, StyleSheet, Text, View } from "react-native";
import {
  setCustomView,
  setCustomTextInput,
  setCustomText,
  setCustomImage,
  setCustomTouchableOpacity
} from "react-native-global-props";

const customTextProps = {
  style: {
    fontSize: 20,
    fontFamily: Platform.OS === "ios" ? "HelveticaNeue" : "Roboto",
    color: "red"
  }
};

setCustomText(customTextProps);

const instructions = Platform.select({
  ios: "Press Cmd+R to reload,\n" + "Cmd+D or shake for dev menu",
  android:
    "Double tap R on your keyboard to reload,\n" +
    "Shake or press menu button for dev menu"
});

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
`

### **and package.json:**

`
"dependencies": {
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-global-props": "^1.1.4"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"
  }
`

> **Any one know the solution?**

**Comment by mr-riiim** [comment]
I find a fix been added for this error on commit [dd3f676](https://github.com/maieonbrix/react-native-global-props/commit/dd3f6766f5a1855d2956ccc4e90783d8ed23deab) , **still i don't have this fix with npm install .** 


i'm using version 1.1.4  , but in node_modules , react-native-global-props packages  , did't get changes !

**Comment by Ajackster** [comment]
@mr-riiim Does the package.json in your node_modules/react-native-global-props say 1.1.4?

**Comment by Balasnest** [comment]
@Ajackster i'm using version 1.1.3. Facing this same issue.
@mr-riiim  Did you manage to get it work?

**Comment by Balasnest** [comment]
@mr-riiim  It works after changing to this in package.json. 
`"react-native-global-props": "Ajackster/react-native-global-props#master",`
@Ajackster I guess some problem with update. Please look into it.

**Comment by Ajackster** [comment]
Will do, thanks guys

**Comment by Ajackster** [comment]
react-native-global-props v 1.1.5 should fix this.
