### ISSUE TITLE
fontWeight not applied to custom font after RN update

### ISSUE THREAD

**Issue by BluDay** [Ajackster/react-native-global-props#2]
Yes the title sums it up...

After I accidentally upgraded or updated react-native in npm and transfered my entire project to a new one, fontWeight stopped working completely with a custom font (Roboto-Thin.ttf).

Thanks :)

**Comment by Ajackster** [comment]
@BluDay what version of react native did you upgrade to?

**Comment by BluDay** [comment]
@Ajackster 

I don't remember because I removed my previous project.
Now on my new project I'm using:

`react-native-cli: 2.0.1
react-native: 0.41.2`
