### ISSUE TITLE
doesn't work for ScrollView keyboardShouldPersistTaps prop

### ISSUE THREAD

**Issue by ivanzotov** [Ajackster/react-native-global-props#5]
Can't set default prop for `keyboardShouldPersistTaps` of ScrollView, any others work

**Comment by Ajackster** [comment]
Good catch. Currently I'm not checking for default props provided by react-native. activeOpacity and underlayColor both have default props, and they're set to override you custom provided props. Working on a fix now. Thanks for the report!

**Comment by Ajackster** [comment]
This is now fixed, published on v1.1.3. Let me know if you have any more problems. :)
