### ISSUE TITLE
appdelegate.m:12:9: 'rctbundleurlprovider.h' file not found

### ISSUE THREAD

**Issue by amitbravo** [Ajackster/react-native-global-props#9]
react-native: 0.55.3
react : 16.3.2
xcode : 9.3 

"react-native-global-props appdelegate.m:12:9: 'rctbundleurlprovider.h' file not found" 
I did update pod file, e.g. pod install ., it did not work.

**Comment by NightWarrior** [comment]
Unlink react-native-global-props and build.
`react-native unlink react-native-global-props`

**Comment by rodrigobdz** [comment]
@NightWarrior I'm still getting the error after unlinking it. How would an unlink help? I'm curious.

**Comment by amitbravo** [comment]
Did you use in app/build.gradle something like:

ext {
    // dependency versions
    googlePlayServicesVersion = "15.0.0" // default: "+"
    compileSdkVersion = 27 // default: 23
    buildToolsVersion = "27.0.3" // default: "25.0.2"
    targetSdkVersion = 27 // default: 22
  }

**Comment by rodrigobdz** [comment]
@amitbravo Not really but unlinking did the trick for me.

**Comment by Ajackster** [comment]
This should be fixed with this [PR](https://github.com/Ajackster/react-native-global-props/pull/15
)
